/*
 * Growser - https://github.com/TheEntropyShard/Growser
 * Copyright (C) 2023-2025 TheEntropyShard
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package me.theentropyshard.growser.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF446732)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC5EFAB)
val onPrimaryContainerLight = Color(0xFF2D4F1C)
val secondaryLight = Color(0xFF55624C)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD9E7CB)
val onSecondaryContainerLight = Color(0xFF3E4A35)
val tertiaryLight = Color(0xFF386666)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBBEBEC)
val onTertiaryContainerLight = Color(0xFF1E4E4E)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF8FAF0)
val onBackgroundLight = Color(0xFF191D16)
val surfaceLight = Color(0xFFF8FAF0)
val onSurfaceLight = Color(0xFF191D16)
val surfaceVariantLight = Color(0xFFE0E4D7)
val onSurfaceVariantLight = Color(0xFF43483E)
val outlineLight = Color(0xFF74796D)
val outlineVariantLight = Color(0xFFC3C8BB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E312B)
val inverseOnSurfaceLight = Color(0xFFF0F2E7)
val inversePrimaryLight = Color(0xFFAAD291)
val surfaceDimLight = Color(0xFFD9DBD1)
val surfaceBrightLight = Color(0xFFF8FAF0)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F5EA)
val surfaceContainerLight = Color(0xFFEDEFE5)
val surfaceContainerHighLight = Color(0xFFE7E9DF)
val surfaceContainerHighestLight = Color(0xFFE1E4D9)

val primaryLightMediumContrast = Color(0xFF1D3E0D)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF52773F)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF2D3A26)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF64715A)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF073D3E)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF477575)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF8FAF0)
val onBackgroundLightMediumContrast = Color(0xFF191D16)
val surfaceLightMediumContrast = Color(0xFFF8FAF0)
val onSurfaceLightMediumContrast = Color(0xFF0F120C)
val surfaceVariantLightMediumContrast = Color(0xFFE0E4D7)
val onSurfaceVariantLightMediumContrast = Color(0xFF33382E)
val outlineLightMediumContrast = Color(0xFF4F544A)
val outlineVariantLightMediumContrast = Color(0xFF6A6F64)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2E312B)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF0F2E7)
val inversePrimaryLightMediumContrast = Color(0xFFAAD291)
val surfaceDimLightMediumContrast = Color(0xFFC5C8BE)
val surfaceBrightLightMediumContrast = Color(0xFFF8FAF0)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF2F5EA)
val surfaceContainerLightMediumContrast = Color(0xFFE7E9DF)
val surfaceContainerHighLightMediumContrast = Color(0xFFDBDED4)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD0D3C9)

val primaryLightHighContrast = Color(0xFF133304)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF30511F)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF242F1C)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF404D38)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF003233)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF215051)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF8FAF0)
val onBackgroundLightHighContrast = Color(0xFF191D16)
val surfaceLightHighContrast = Color(0xFFF8FAF0)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE0E4D7)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF292E25)
val outlineVariantLightHighContrast = Color(0xFF464B41)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2E312B)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFAAD291)
val surfaceDimLightHighContrast = Color(0xFFB7BAB0)
val surfaceBrightLightHighContrast = Color(0xFFF8FAF0)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF0F2E7)
val surfaceContainerLightHighContrast = Color(0xFFE1E4D9)
val surfaceContainerHighLightHighContrast = Color(0xFFD3D5CB)
val surfaceContainerHighestLightHighContrast = Color(0xFFC5C8BE)

val primaryDark = Color(0xFFAAD291)
val onPrimaryDark = Color(0xFF173807)
val primaryContainerDark = Color(0xFF2D4F1C)
val onPrimaryContainerDark = Color(0xFFC5EFAB)
val secondaryDark = Color(0xFFBDCBB0)
val onSecondaryDark = Color(0xFF283420)
val secondaryContainerDark = Color(0xFF3E4A35)
val onSecondaryContainerDark = Color(0xFFD9E7CB)
val tertiaryDark = Color(0xFFA0CFD0)
val onTertiaryDark = Color(0xFF003738)
val tertiaryContainerDark = Color(0xFF1E4E4E)
val onTertiaryContainerDark = Color(0xFFBBEBEC)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF11140F)
val onBackgroundDark = Color(0xFFE1E4D9)
val surfaceDark = Color(0xFF11140F)
val onSurfaceDark = Color(0xFFE1E4D9)
val surfaceVariantDark = Color(0xFF43483E)
val onSurfaceVariantDark = Color(0xFFC3C8BB)
val outlineDark = Color(0xFF8D9286)
val outlineVariantDark = Color(0xFF43483E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E4D9)
val inverseOnSurfaceDark = Color(0xFF2E312B)
val inversePrimaryDark = Color(0xFF446732)
val surfaceDimDark = Color(0xFF11140F)
val surfaceBrightDark = Color(0xFF373A33)
val surfaceContainerLowestDark = Color(0xFF0C0F0A)
val surfaceContainerLowDark = Color(0xFF191D16)
val surfaceContainerDark = Color(0xFF1D211A)
val surfaceContainerHighDark = Color(0xFF282B24)
val surfaceContainerHighestDark = Color(0xFF32362F)

val primaryDarkMediumContrast = Color(0xFFBFE8A5)
val onPrimaryDarkMediumContrast = Color(0xFF0C2C00)
val primaryContainerDarkMediumContrast = Color(0xFF759B60)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFD2E1C5)
val onSecondaryDarkMediumContrast = Color(0xFF1D2916)
val secondaryContainerDarkMediumContrast = Color(0xFF87957C)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFB5E5E6)
val onTertiaryDarkMediumContrast = Color(0xFF002B2C)
val tertiaryContainerDarkMediumContrast = Color(0xFF6B9999)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF11140F)
val onBackgroundDarkMediumContrast = Color(0xFFE1E4D9)
val surfaceDarkMediumContrast = Color(0xFF11140F)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF43483E)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD9DED0)
val outlineDarkMediumContrast = Color(0xFFAFB4A7)
val outlineVariantDarkMediumContrast = Color(0xFF8D9286)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE1E4D9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF282B24)
val inversePrimaryDarkMediumContrast = Color(0xFF2E501D)
val surfaceDimDarkMediumContrast = Color(0xFF11140F)
val surfaceBrightDarkMediumContrast = Color(0xFF42463E)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF060804)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1B1F18)
val surfaceContainerDarkMediumContrast = Color(0xFF252922)
val surfaceContainerHighDarkMediumContrast = Color(0xFF30342D)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3B3F38)

val primaryDarkHighContrast = Color(0xFFD2FCB7)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFA6CE8D)
val onPrimaryContainerDarkHighContrast = Color(0xFF020E00)
val secondaryDarkHighContrast = Color(0xFFE6F5D8)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFB9C7AC)
val onSecondaryContainerDarkHighContrast = Color(0xFF040E02)
val tertiaryDarkHighContrast = Color(0xFFC9F9F9)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF9CCBCC)
val onTertiaryContainerDarkHighContrast = Color(0xFF000E0E)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF11140F)
val onBackgroundDarkHighContrast = Color(0xFFE1E4D9)
val surfaceDarkHighContrast = Color(0xFF11140F)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF43483E)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEDF2E4)
val outlineVariantDarkHighContrast = Color(0xFFBFC4B7)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE1E4D9)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF2E501D)
val surfaceDimDarkHighContrast = Color(0xFF11140F)
val surfaceBrightDarkHighContrast = Color(0xFF4E514A)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1D211A)
val surfaceContainerDarkHighContrast = Color(0xFF2E312B)
val surfaceContainerHighDarkHighContrast = Color(0xFF393C35)
val surfaceContainerHighestDarkHighContrast = Color(0xFF444840)
